apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- if not .Values.skipLabels }}
    {{- include "gadget.labels" . | nindent 4 }}
    {{- end }}
    k8s-app: {{ include "gadget.fullname" . }}
  name: {{ include "gadget.fullname" . }}
  namespace: {{ include "gadget.namespace" . }}
