apiVersion: v1
kind: ServiceAccount
metadata:
  name: bcc-shell
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bcc-shell
subjects:
- kind: ServiceAccount
  name: bcc-shell
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bcc-shell
  labels:
    k8s-app: bcc-shell
spec:
  selector:
    matchLabels:
      name: bcc-shell
  template:
    metadata:
      labels:
        name: bcc-shell
    spec:
      serviceAccount: bcc-shell
      hostNetwork: true
      containers:
      - name: bcc-shell
        image: docker.io/zlim/bcc
        command: [ "/bin/sh", "-c", "sleep 1000000" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: modules
          mountPath: /lib/modules
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: modules
        hostPath:
          path: /lib/modules
      - name: src
        hostPath:
          path: /usr/src
      - name: localtime
        hostPath:
          path: /etc/localtime
