apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: privileged1-pod
  labels:
    k8s-app: privileged1-pod
spec:
  selector:
    matchLabels:
      name: privileged1-pod
      myapp: app-one
      role: demo
  template:
    metadata:
      labels:
        name: privileged1-pod
        myapp: app-one
        role: demo
    spec:
      hostNetwork: true
      containers:
      - name: privileged1-pod
        image: docker.io/albanc/toolbox
        command: [ "sh", "-c", "while /bin/true ; do date ; cat /proc/version ; sleep 1 ; done" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: privileged2-pod
  labels:
    k8s-app: privileged2-pod
spec:
  selector:
    matchLabels:
      name: privileged2-pod
      myapp: app-two
      role: demo
  template:
    metadata:
      labels:
        name: privileged2-pod
        myapp: app-two
        role: demo
    spec:
      hostNetwork: true
      containers:
      - name: privileged2-pod
        image: docker.io/albanc/toolbox
        command: [ "sh", "-c", "while /bin/true ; do date ; /bin/echo sleep-10 ; /bin/sleep 10 ; done" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
