apiVersion: v1
kind: ServiceAccount
metadata:
  name: straceback
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: straceback
subjects:
- kind: ServiceAccount
  name: straceback
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: straceback
  labels:
    k8s-app: straceback
spec:
  selector:
    matchLabels:
      name: straceback
  template:
    metadata:
      labels:
        name: straceback
    spec:
      serviceAccount: straceback
      hostNetwork: true
      containers:
      - name: straceback
        image: docker.io/kinvolk/straceback:latest
        command: [ "/bin/sh", "-c", "rm -f /run/straceback.socket && /bin/straceback serve" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: run
          mountPath: /run
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: bpffs
          mountPath: /sys/fs/bpf
        - name: localtime
          mountPath: /etc/localtime
      volumes:
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: localtime
        hostPath:
          path: /etc/localtime
