version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "go:"
  - package-ecosystem: "docker"
    directory: "/Dockerfiles"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dockerfiles:"
