name: "Install debian packages"
description: "Install debian packages needed by inspektor-gadget"

inputs:
  libseccomp-version:
    description: "Version of the libseccomp to install."
    default: "2.5.3-2ubuntu2"

runs:
  using: "composite"
  steps:
    - name: Cache debian packages
      uses: actions/cache@v3.0.11
      id: cache-debs
      with:
        path: "~/cache-debs"
        # Any changes to this file or main workflow file will invalidate the
        # cache.
        key: ${{ hashFiles('.github/actions/install-debian-packages/action.yml', '.github/workflows/inspektor-gadget.yml') }}
    - name: Install debian packages
      shell: bash
      run: |
        if [[ "${{steps.cache-debs.outputs.cache-hit}}" == 'true' ]]; then
          sudo cp --verbose --force --recursive ~/cache-debs/* /
        else
          sudo apt-get update
          sudo apt-get install -y libseccomp-dev="${{inputs.libseccomp-version}}"
          mkdir -p ~/cache-debs
          sudo dpkg -L libseccomp-dev | \
              while IFS= read -r f; do \
                  if test -f $f; then echo $f; fi; \
              done | xargs cp --parents --target-directory ~/cache-debs/
        fi
