apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-labels-to-bpf
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-labels-to-bpf
subjects:
- kind: ServiceAccount
  name: k8s-labels-to-bpf
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-labels-to-bpf
  labels:
    k8s-app: k8s-labels-to-bpf
spec:
  selector:
    matchLabels:
      name: k8s-labels-to-bpf
  template:
    metadata:
      labels:
        name: k8s-labels-to-bpf
    spec:
      serviceAccount: k8s-labels-to-bpf
      hostNetwork: true
      containers:
      - name: proc-sync
        image: docker.io/albanc/k8s-labels-to-bpf:latest
        env:
        - name: HOSTPROC
          value: "/hostproc"
        command: [ "/bin/k8s-labels-to-bpf" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
        - name: bpffs
          mountPath: /sys/fs/bpf
      - name: k8s-sync
        image: docker.io/albanc/k8s-labels-to-bpf:latest
        command: [ "/bin/sh", "-c", "/bin/create-map.sh ; while true ; do sleep 15 ; /bin/update-labels.sh ; done" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
        - name: bpffs
          mountPath: /sys/fs/bpf
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
