apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-labels-to-bpf
  labels:
    k8s-app: k8s-labels-to-bpf
spec:
  selector:
    matchLabels:
      name: k8s-labels-to-bpf
  template:
    metadata:
      labels:
        name: k8s-labels-to-bpf
    spec:
      hostNetwork: true
      containers:
      - name: proc-sync
        image: docker.io/albanc/k8s-labels-to-bpf:latest
        command: [ "/bin/k8s-labels-to-bpf" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
        - name: bpffs
          mountPath: /sys/fs/bpf
      - name: k8s-sync
        image: docker.io/albanc/k8s-labels-to-bpf:latest
        command: [ "/bin/sh", "-c", "/bin/create-map.sh ; sleep 1000" ]
        securityContext:
          privileged: true
        volumeMounts:
        - name: hostproc
          mountPath: /hostproc
        - name: bpffs
          mountPath: /sys/fs/bpf
      volumes:
      - name: hostproc
        hostPath:
          path: /proc
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
