name: Min Inspektor Gadget CI
env:
  REGISTRY: ghcr.io
  CONTAINER_REPO: ${{ github.repository }}
  GO_VERSION: 1.22.8

on:
  pull_request:
  push:
    branches:
      - main

permissions: read-all

jobs:
  gadgets-unittest:
    name: Gadgets unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set container repository and determine image tag
        id: set-repo-determine-image-tag
        uses: ./.github/actions/set-container-repo-and-determine-image-tag
        with:
          registry: ${{ env.REGISTRY }}
          container-image: ${{ env.CONTAINER_REPO }}
      - name: Setup go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
        id: go
      - name: Gadgets tests
        id: gadgets-tests
        shell: bash
        env:
          IG_VERIFY_IMAGE: false
        run: |
            set -o pipefail
            make -C gadgets/ test-unit -o build |& tee gadgets-tests.log & wait $!
      - name: Prepare and publish test reports
        if: always()
        continue-on-error: true
        uses: ./.github/actions/prepare-and-publish-test-reports
        with:
          test-log-file: gadgets-tests.log
          test-step-conclusion: ${{ steps.gadgets-tests.conclusion }}
          test-summary-suffix: "gadgets-unittest"
